[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "merging-eval"
version = "0.1.1"
description = "Model Merging Scaling Laws in Large Language Models - Empirical scaling laws for language model merging measured by cross-entropy"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Merging-EVAL Team", email = "maxuan1798@gmail.com"}
]
keywords = ["llm", "model-merging", "scaling-laws", "language-models", "cross-entropy"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "transformers>=4.30.0",
    "datasets>=2.12.0",
    "accelerate>=0.20.0",
    "pandas>=2.0.0",
    "tqdm>=4.65.0",
    "requests>=2.31.0",
]

[project.optional-dependencies]
full = [
    "torch==2.6.0",
    "torchaudio==2.6.0",
    "torchvision==0.21.0",
    "transformers==4.50.1",
    "datasets==3.4.1",
    "tokenizers==0.21.1",
    "huggingface-hub==0.29.3",
    "safetensors==0.5.3",
    "pyarrow==19.0.1",
    "swanlab>=0.3.0",
    "bitsandbytes==0.45.4",
    "peft==0.15.0",
    "deepspeed==0.16.4",
    "vllm==0.8.2",
    "triton==3.2.0",
    "xformers==0.0.29.post2",
    "flashinfer-python==0.2.3",
    "ninja==1.11.1.4",
    "compressed-tensors==0.9.2",
    "gguf==0.10.0",
    "trl==0.15.2",
    "unsloth==2025.3.18",
    "unsloth_zoo==2025.3.16",
    "outlines==0.1.11",
    "outlines_core==0.1.26",
    "lm-format-enforcer==0.10.11",
    "llguidance==0.7.10",
    "xgrammar==0.1.16",
    "diffusers==0.32.2",
    "opencv-python-headless==4.11.0.86",
    "pillow==11.1.0",
    "cupy-cuda12x==13.4.1",
    "nvidia-ml-py==12.570.86",
    "fastapi==0.115.12",
    "uvicorn==0.34.0",
    "starlette==0.46.1",
    "pydantic==2.10.6",
    "wandb==0.19.8",
    "prometheus-client==0.21.1",
    "prometheus-fastapi-instrumentator==7.1.0",
    "nvitop==1.4.2",
    "ray==2.44.0",
    "scipy==1.15.2",
    "scikit-learn==1.6.1",
    "numba==0.60.0",
    "llvmlite==0.43.0",
    "matplotlib==3.10.1",
    "seaborn==0.13.2",
    "click==8.1.8",
    "rich==13.9.4",
    "typer==0.15.2",
    "pyyaml==6.0.2",
    "python-dotenv==1.1.0",
    "httpx==0.28.1",
    "aiohttp==3.11.14",
    "openai==1.68.2",
    "einops==0.8.1",
    "sentencepiece==0.2.0",
    "tiktoken==0.9.0",
    "protobuf==3.20.3",
    "psutil==7.0.0",
    "filelock==3.18.0",
    "regex==2024.11.6",
    "packaging==24.2",
    "fsspec==2024.12.0",
]

[project.urls]
Homepage = "https://github.com/Merging-EVAL/Merging-EVAL"
Documentation = "https://github.com/Merging-EVAL/Merging-EVAL#readme"
Repository = "https://github.com/Merging-EVAL/Merging-EVAL"
Issues = "https://github.com/Merging-EVAL/Merging-EVAL/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["merge*", "expert_training*"]

[tool.setuptools.package-data]
"*" = ["*.txt", "*.json", "*.yaml", "*.yml"]

[project.scripts]
merging-eval = "merge.main_merging:main"

